exercise/urls.py
#coding: utf-8
from django.conf.urls import patterns, url
from exercise import views


urlpatterns = patterns('',
    url(r'(?P<pk>[0-9]+)/$', views.ExerciseView.as_view(), name='exercise_subject'),
    url(r'list/$', views.ExerciseListView.as_view(), name='exercise_list'),
    url(r'submit/$', views.SubmitView.as_view(), name='submit'),
)

learnc/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.base import TemplateView
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'learnc.views.home', name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='about.html'), name='about'),
    # url(r'^learnc/', include('learnc.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^step/', include('stepbystep.urls')),
    url(r'^exercise/', include('exercise.urls')),
    url(r'^commtents/', include('django.contrib.comments.urls')),
)

exercise/models.py
# coding: utf-8
import os
import json
from django.db import models
from django.contrib.auth.models import User

from django.conf import settings


class ExerciseManager(models.Manager):
    def create_detail(self, rel_user, form_data):
        exercise = self.create(
            user=rel_user,
            title=form_data['title'],
            content=form_data['content'],
            input_text=form_data['input_text'],
            output_text=form_data['output_text'],
        )
        return exercise


class Exercise(models.Model):
    SORT_CHOICES = (
        #练习
        (1, '顺序结构'),
        (2, '选择结构'),
        (3, '循环结构'),
        (4, '数组'),
        (5, '指针'),
        (6, '结构体'),
        #作业
        (7, '作业'),
        #考试
        (8, '考试'),
    )

    user = models.ForeignKey(User, verbose_name="创建的用户")
    title = models.CharField("练习题名", max_length=64)
    content = models.TextField("练习题目", max_length=512)
    input_text = models.TextField("输入", max_length=512, blank=True)
    output_text = models.TextField("程序预定输出", max_length=512)
    create_time = models.DateTimeField("创建时间", auto_now_add=True)
    total_submit = models.IntegerField("总提交次数", default=0)
    success_submit = models.IntegerField("正确提交的次数", default=0)
    sort = models.IntegerField("题目分类", choices=SORT_CHOICES, default=1)


    objects = ExerciseManager()

    def __unicode__(self):
        return self.title

    def save(self, *args, **kwargs):
        super(Exercise, self).save(*args, **kwargs)
        code_path = os.path.join(settings.ROOT, 'code')
        input_path = os.path.join(code_path, 'input')
        #output_path = os.path.join(code_path, 'output')
        input_file = input_path + '/' + str(self.id) + '.input'
        #output_file = output_path + '/' + str(self.id) + '.output'
        f = open(input_file, 'w')
        f.write(self.input_text)
        f.close()
        #f = open(output_file, 'w')
        #f.write(self.output_text)
        #f.close()


class SubmitManager(models.Manager):
    def create_submit(self, rel_user, form_data):
        exercise = self.create(
            user=rel_user,
            exercise=form_data['exercise'],
            code=form_data['code'],
            cpu_time=form_data['cpu_time'],
            mem=form_data['mem'],
            status=form_data['status'],
        )
        return exercise


class Submit(models.Model):
    STATUS_CHOICES = (
        (1, '编译失败'),
        (2, '逻辑错误'),
        (3, '成功'),
        (4, '运行错误'),
        (5, '未知错误'),
        (6, '正在编译'),
    )
    user = models.ForeignKey(User, verbose_name="提交答案的学生")
    exercise = models.ForeignKey(Exercise, verbose_name="提交的哪一个题")
    code = models.CharField("提交的代码", max_length=1024)
    cpu_time = models.IntegerField("cpu执行时间,ms", default=0)
    mem = models.IntegerField("消耗内存,kb", default=0)
    status = models.IntegerField("代码状态", choices=STATUS_CHOICES, default=6)
    create_time = models.DateTimeField("创建时间", auto_now_add=True)

    objects = SubmitManager()

    def __unicode__(self):
        return '%s-%s' % (self.user.username, self.exercise.title)

mycomment/models.py
# coding: utf-8
from django.db import models
from django.contrib.comments.models import BaseCommentAbstractModel
from django.contrib.auth.models import User


class Comment(BaseCommentAbstractModel):
    comment = models.TextField('评论', max_length=300)
    user = models.ForeignKey(User)

exercise/views.py
# coding: utf-8
import os
import json
import commands
from django.http import HttpResponse
from django.views.generic import DetailView, View
from django.views.generic.list import ListView
from django.shortcuts import get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from django.conf import settings
from exercise.models import Exercise, Submit
from exercise import run


class ExerciseView(DetailView):
    model = Exercise

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(ExerciseView, self).dispatch(request, *args, **kwargs)

class ExerciseListView(ListView):
    model = Exercise
    paginate_by = '10'
    context_object_name = 'exercises'


class SubmitView(View):
    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(SubmitView, self).dispatch(request, *args, **kwargs)

    def post(self, request):
        user = request.user
        data = {}
        code = request.POST['code']
        exercise_id = request.POST['exercise_id']
        exercise = get_object_or_404(Exercise, id=exercise_id)
        exercise.total_submit += 1
        user.total.total_submit += 1
        submit = Submit(
            user=user,
            exercise=exercise,
            code=code,
            code_len=len(code),
        )
        submit.save()
        #编译执行需要独立执行，容易超时:
        code_path = os.path.join(settings.ROOT, 'code')
        pre_name = '/' + str(exercise.id) + '_' + str(submit.id)
        code_filepath = os.path.join(code_path, 'code') + pre_name + '.c'
        f = open(code_filepath, 'w')
        f.write(code)
        f.close()
        data['status'] = True

        exe = os.path.join(code_path, 'exe') + pre_name

        input_file = os.path.join(code_path, 'input') + '/' + str(exercise.id) + '.input'
        output_file = os.path.join(code_path, 'output') + pre_name + '.output'
        err_file = os.path.join(code_path, 'error') + pre_name + '.error'

        command = 'gcc ' + code_filepath + ' -o ' + exe
        #make_result = os.popen(command).read()
        make_result = commands.getoutput(command)
        #替换掉路径
        make_result = make_result.replace(code_path, '')
        #print repr(make_result)
        if make_result:
            submit.mem = 0
            submit.status = 1
            stderr = open(err_file, 'w')
            stderr.write(str(make_result))
            stderr.close()
            pass
        else:
            stdin = open(input_file, 'r')
            stdout = open(output_file, 'w')
            stderr = open(err_file, 'w')
            result = run.exe_main(exe, stdin, stdout, stderr)
            stdin.close()
            stdout.close()
            stderr.close()
            submit.mem = result['mem']
            submit.cpu_time = result['cpu']
            run_result = result['result']
            #判断执行结果是否成功
            if run_result != "OK":
                submit.status = 4
            else:
                f = open(output_file, 'r')
                output_result = f.read()
                if output_result == exercise.output_text:
                    submit.status = 3
                    exercise.success_submit += 1
                    user.total.success_submit += 1
                else:
                    submit.status = 2
            f.close()
        submit.save()
        user.total.save()
        exercise.save()
        return HttpResponse(json.dumps(data), content_type="application/json")

templates/exercise/exercise_detail.html
{% extends "accounts/base.html" %}
{% load static %}
{% load stepbystep_extras %}

{% block css1 %}
<style type="text/css" media="screen">

.ace_marker-layer .ace_selection {
    position: absolute;
    z-index: 40;
    background: rgb(181, 213, 255);
}
.mark {background: red;}
   #display { 
        position: absolute;
        top: 0;
        right: 0;
        bottom: 0;
        left: 0;
    }
   #editor { 
        position: absolute;
        top: 0;
        right: 0;
        bottom: 0;
        left: 0;
    }
    #content{
        width: 620px;
        height: 100px;
        position: relative;

    }
</style>
{% endblock %}


{% block span8 %}

<div class="tabbable">
<ul id="mytab" class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#exercise">题目</a></li>
    <li><a data-toggle="tab" href="#result">结果</a></li>
    <li><a data-toggle="tab" href="#comment">讨论</a></li>
</ul>

<div class="tab-content">

<div class="tab-pane active" id="exercise">
<div>
    </br>
<h5>{{ exercise.title }}</h5>
</div>


<div class="alert alert-info">
<span class="badge badge-info">题目</span>
{{ exercise.content|safe|code_strong }}
</div>


{% if user.is_authenticated %}
<div id="content">
<div id="editor">#include "stdio.h"
int main(){
    int a, b;
    while (scanf("%d %d", &a, &b)==2)
        printf("%d\n",a+b);
    return 0;
}</div>
</div>
</br>
</br>
<button id="submit-code-btn" class="btn btn-primary pull-right" type="button">提交</button>
<script src="{% static 'ace/ace.js' %}" type="text/javascript" charset="utf-8"></script>
<script>
    var exercise_id = {{ exercise.id }};
    function getCookie(sName){
        var aCookie=document.cookie.split("; ");
        for(var i=0;i<aCookie.length;i++){var aCrumb=aCookie[i].split("=");if(sName==aCrumb[0])
        return(aCrumb[1]);}return null;
    }

    var editor = ace.edit("editor");
    editor.setTheme("ace/theme/monokai");
    editor.getSession().setMode("ace/mode/c_cpp");
    document.getElementById('editor').style.fontSize='18px';
    //editor.setKeyboardHandler("ace/keyboard/vim");
    editor.renderer.setShowGutter(true);
    $("#submit-code-btn").click(function(){
        var code = editor.getValue();
        console.log(code)
        $.post('{% url 'submit' %}',
        {'code':code,"exercise_id":exercise_id,"csrfmiddlewaretoken":getCookie('csrftoken')},
        function(data,status){
            console.log(data)
        });
    });
</script>
{% else %}
<div class="alert alert-error">
<p>做题请先<a href="{% url 'login' %}">登录</a></p>
</div>

{% endif %}

</div>

<div class="tab-pane" id="result">
   
{% if user.is_authenticated %}
<table class="table table-striped table-bordered table-hover">
<tbody>
<tr>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>

<script>
$('a[data-toggle="tab"]').on('shown', function (e) {
    console.log(e.target.href) // 当前活动的标签
}) 
</script>
{% else %}
<div class="alert alert-error">
<p>请先<a href="{% url 'login' %}">登录</a>,然后查看提交结果</p>
</div>
{% endif %}

</div>

{% load comments %}
{% get_comment_list for exercise as comment_list %}
<div class="tab-pane" id="comment">
    <div class="span8">
        {% for comment in comment_list %}
        <div class="span8">
        <div class="row-fluid">
            <div class="span4"><h6>{{ comment.user }}</h6></div>
            <div class="span4 pull-right"><h6>{{ comment.submit_date|date:"Y-m-d H:i:s" }}</h6></div>
        </div>
        <br>
        {{ comment.comment }}<hr></div>
        {% endfor %}
    </div>
{% if user.is_authenticated %}
{% get_comment_form for exercise as form %}
<div class="span6">
<form class="form-signin" method="post" action="{% comment_form_target %}">
    {% csrf_token %}
    {{ form.comment }}
    {{ form.content_type }}
    {{ form.object_pk }}
    {{ form.timestamp }}
    {{ form.security_hash }}
    <input type="hidden" name="next" value="{% url 'exercise_subject' exercise.id %}" />
    <button type="submit" class="btn btn-large btn-primary">提交</button>
</form>
<div>
{% else %}
<div class="alert alert-error">
<p>评论请先<a href="{% url 'login' %}">登录</a></p>
</div>
{% endif %}

</div>

</div>
</div>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}" type="text/javascript" charset="utf-8"></script>
{% endblock %}

templates/exercise/exercise_list.html
{% extends "accounts/base.html" %}

{% block span8 %}

<table class="table table-striped table-bordered table-hover">
<thead>
                <tr>
                  <th>#</th>
                  <th>题目</th>
                  <th>提交次数</th>
                  <th>通过率</th>
                </tr>
              </thead>
<tbody>
{% for exercise in exercises %}
<tr>
<td>{{ exercise.id }}</td>
<td><a href="{% url 'exercise_subject' exercise.id %}">{{ exercise.title }}</a></td>
<td>{{ exercise.create_time|date:"Y-m-d H:i:s" }}</td>
<td></td>
</tr>
{% endfor %}
</tbody>
</table>
<div class="pagination">
<ul>
{% if paginator.has_previous %}
<li><a href="?page={{ paginator.previous_page_number }}">前一页</a></li>
{% else %}
<li class="disabled"><a href="#">前一页</a></li>
{% endif %}
{% for pg in paginator.page_range %}
{% if paginator.number == pg %}
<li class="active"><a href="?page={{ pg }}">{{ pg }}</a></li>
{% else %}
<li><a href="?page={{ pg }}">{{ pg }}</a></li>
{% endif %}
{% endfor %}
{% if paginator.has_next %}
<li><a href="?page={{ paginator.next_page_number }}">后一页</a></li>
{% else %}
<li class="disabled"><a href="#">后一页</a></li>
{% endif %}
</ul>
</div>
{% endblock %}